// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	model "banking_ledger/gateway-service/models"

	mock "github.com/stretchr/testify/mock"
)

// IAccountService is an autogenerated mock type for the IAccountService type
type IAccountService struct {
	mock.Mock
}

// CreateAccount provides a mock function with given fields: account
func (_m *IAccountService) CreateAccount(account *model.Account) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Account) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAccountService creates a new instance of IAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAccountService {
	mock := &IAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
