// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	model "banking_ledger/gateway-service/models"

	mock "github.com/stretchr/testify/mock"
)

// ICustomerService is an autogenerated mock type for the ICustomerService type
type ICustomerService struct {
	mock.Mock
}

// CreateCustomer provides a mock function with given fields: customer
func (_m *ICustomerService) CreateCustomer(customer *model.Customer) error {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Customer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCustomerByID provides a mock function with given fields: customerID
func (_m *ICustomerService) GetCustomerByID(customerID string) (*model.Customer, error) {
	ret := _m.Called(customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerByID")
	}

	var r0 *model.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.Customer, error)); ok {
		return rf(customerID)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Customer); ok {
		r0 = rf(customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICustomerService creates a new instance of ICustomerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICustomerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICustomerService {
	mock := &ICustomerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
