mock:
	mockery --dir=service --name=IAccountService  --output=service/test/mocks
	mockery --dir=service --name=ICustomerService  --output=service/test/mocks
	mockery --dir=service --name=ITransactionService  --output=service/test/mocks
	mockery --dir=repo --name=AccountRepository  --output=repo/test/mocks
	mockery --dir=repo --name=CustomerRepository  --output=repo/test/mocks
	mockery --dir=repo --name=TransactionRepository  --output=repo/test/mocks
	mockery --dir=config --name=KafkaProducer  --output=config/mocks
